### PR TITLE
Remove errors on TypeScript project

### PR DESCRIPTION
**Pull request by tommasoresti**

### CODE REVIEW

**Comment by mapu77** [comment]
Hi, @TommyDevAll thanks for the pull request. 

As far as I see some of your commits you are adding/modifying some of the operations contracts such as `getById(id: number): Order` in `OrderRepository.ts`. This makes you add new behaviour in the use cases changing their behaviour. When @sergiowalls and I translated this kata to TypeScript we wanted it to be as similar as possible to its original in Java (i.e. including unnecessary methods, attributes, or incorrect language conventions) so that the those refactors became also part of the exercise.

On the other hand, I see you updated the typescript configuration to ES6 and add NodeJS as the test environment. Thanks for adding that! 

This pull request contains different types of changes at the same time. In order to keep the behaviour of the classes as they were in the original code, we won't merge it, but if you want to create a new pull request to keep contributing by improving the test environment and adding ES6, that's totally fine and we really appreciate it.

Greetings

**Comment by tommasoresti** [comment]
Hi Eduard. The problem with the current code is that is that was not
compiling because of some method that can return 'undefined'. For example,
the 'find' method in the order repository can return undefined.

The main purpose of my PR was to make it clear that a repository can return
a nullable object and remove these kind of errors.

Does the project compile for you right now?

Il giorno mer 12 dic 2018, 20:33 Eduard Maura i Puig <
notifications@github.com> ha scritto:

**Comment by mapu77** [comment]
Hi Tommy, it's strange that it compiled for me, maybe I'm ignoring some configuration files but I'm not aware of which ones...

Could you give me more information about what happens when you try to run `npm test`?

**Comment by tommasoresti** [comment]
[image: Screenshot 2018-12-18 at 15.09.32.png]

**Comment by tommasoresti** [comment]
this is when i run 'npm run test'
[image: Screenshot 2018-12-18 at 15.12.40.png]

**Pull request closed without merging**
